// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kenarivsjiesrulamtry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtlbmFyaXZzamllc3J1bGFtdHJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNTQwOTYsImV4cCI6MjA2MDYzMDA5Nn0.ERLMWFuTwUk1B2z1fVcutyuUcZvUOCu_IN-KHjRcBck";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);